### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by jbrucker** [ttxking/ttxking#1]
In your clever README file, "CyberSecruity" should be "CyberSecurity" (letters transposed).

What resource(s) do you recommend for studying cyber-security?

**Comment by ttxking** [comment]
Thank you for the correction. 

I would suggest the Cisco netacademy for studying cyber-security. They provide many good resources concerning the topics.
 
Here is one of the examples:
https://www.netacad.com/courses/cybersecurity
